### ISSUE TITLE
What volume can I mount to store the queue data?

### ISSUE THREAD

**Issue by justinmchase** [graze/docker-sqs-local#1]
I want to be able to create the queues and shutdown docker and start it back up and have the queues remain. I'm hoping I can just mount a volume and have this persist between runs.

**Comment by biggianteye** [comment]
This docker image uses [elasticmq](https://github.com/softwaremill/elasticmq) and unfortunately I can't see any indication that it supports persisting of queue that are dynamically created via the `CreateQueue` command. It *does* support creating queues at startup though:

https://github.com/softwaremill/elasticmq#automatically-creating-queues-on-startup

Is that the kind of thing you are after?

**Comment by justinmchase** [comment]
Yeah I was hoping to find a way to persist the queues that were dynamically created and I couldn't find a way either. Looking at the file system I couldn't see any indication that it was writing the new queues to disk.

I guess I'll go with the static way for now

**Comment by biggianteye** [comment]
You might consider bumping this issue, but it's unclear if that will have any effect: https://github.com/softwaremill/elasticmq/issues/40
